[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "slurm-client"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
asyncssh = ">=2.22.0,<3"
httpx = ">=0.28.1,<0.29"
h2 = ">=4.3.0,<5"
socksio = ">=1.0.0,<2"
textual = ">=8.2.4,<9"
rich-click = ">=1.9.7,<2"
textual-plotext = ">=1.0.1,<2"

[pypi-dependencies]
slurm-client = { path = ".", editable = true }

[feature.py313.dependencies]
python = "3.13.*"

[feature.docs.dependencies]
sphinx = "*"
furo = "*"

[feature.dev.dependencies]
black = ">=26.3.1,<27"
pyinstrument = "*"
ipython = ">=9.13.0,<10"
ipdb = "*"
isort = ">=8.0.1,<9"
textual-dev = ">=1.8.0,<2"

[feature.py314.dependencies]
python = "3.14.*"

[feature.tests.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.tests.tasks]
tests = { cmd = "pytest --cov=slurm_client", cwd = "." }

[environments]
docs = ["docs", "py313"]
default = ["dev", "py314"]
tests = ["tests"]
